# Generated by Django 3.1.7 on 2021-09-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.IntegerField()),
                ('provider', models.CharField(max_length=1000)),
                ('merchant_info', models.JSONField(default=dict)),
            ],
        ),
    ]
