# Generated by Django 3.1.7 on 2021-09-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='merchant',
            name='flag2',
            field=models.IntegerField(default=0),
        ),
    ]
