# Generated by Django 3.1.7 on 2021-11-25 06:08

from django.db import migrations, models
import django_payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_payments', '0002_auto_20210913_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.IntegerField(default=0)),
                ('unique_id', models.IntegerField()),
                ('customer_info', models.JSONField(default=dict)),
                ('flag', models.IntegerField(default=0)),
                ('flag2', models.IntegerField(default=0)),
            ],
            bases=(models.Model, django_payments.models.Bitmap),
        ),
    ]
